# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55bf971252e0e2d2bcfccedf5d9a45431af0b6c0ec7bcb92467f287cd9bddf3e90179a1129691ee885a70f0ed4d9ed07fb26c8fba905cec81dae65146bed0d8c

test:
  secret_key_base: bca34d4175f6e69a0f0f6d77be014ea7defa89d71449ecfab8952d2f24610f175147e01b4062728b53568d2b8fb58107a5e2ad9fb647715f786f3ae46bc8b6d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
